### ISSUE TITLE
Transparency doesn't turn off

### ISSUE THREAD

**Issue by Varusal** [vhanla/TaskbarDock#4]
If I uncheck the transparency option the taskbar is still transparent.
Even if `Transparent=0` is set.

**Comment by 4dams** [comment]
Have you tried restarting the explorer? Also, waiting a few seconds did the job for me!

**Comment by SirMorokei** [comment]
Yes sadly didn't fixed it. The only solution that worked for me was to disable and enable the transparency effect in the settings app.
[https://imgur.com/sm9lbBq](https://imgur.com/sm9lbBq)

**Comment by vhanla** [comment]
Commit cfe6324b6235f85a1984b0ffb950b7d287f3c22a solves that. 
There is no executable yet. But you can compile it to test.

**Comment by vhanla** [comment]
This release includes that fix
https://github.com/vhanla/TaskbarDock/tree/v0.1.62

**Comment by Sok00** [comment]
[https://github.com/TranslucentTB/TranslucentTB](https://github.com/TranslucentTB/TranslucentTB)
if helps
